//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPort_Emp
    {
        public MyPort_Emp()
        {
            this.MyPort_EmpDept = new HashSet<MyPort_EmpDept>();
            this.MyPort_EmpStation = new HashSet<MyPort_EmpStation>();
            this.Process_BasicData = new HashSet<Process_BasicData>();
            this.Process_GroupMember = new HashSet<Process_GroupMember>();
        }
    
        public int Id { get; set; }
        public string EmpNo { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public string SID { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Type { get; set; }
        public string FK_Dept { get; set; }
    
        public virtual ICollection<MyPort_EmpDept> MyPort_EmpDept { get; set; }
        public virtual ICollection<MyPort_EmpStation> MyPort_EmpStation { get; set; }
        public virtual MyPort_Student MyPort_Student { get; set; }
        public virtual MyPort_Tutor MyPort_Tutor { get; set; }
        public virtual ICollection<Process_BasicData> Process_BasicData { get; set; }
        public virtual ICollection<Process_GroupMember> Process_GroupMember { get; set; }
        //
        public string FK_DeptName { get; set; }

    }
}
