//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPort_Station
    {
        public MyPort_Station()
        {
            this.MyPort_EmpStation = new HashSet<MyPort_EmpStation>();
        }
    
        public int Id { get; set; }
        public string StaNo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StaGrade { get; set; }
    
        public virtual ICollection<MyPort_EmpStation> MyPort_EmpStation { get; set; }
    }
}
