//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Project
    {
        public Process_Project()
        {
            this.Process_Subject_XuQiuFenXi = new HashSet<Process_Subject_XuQiuFenXi>();
        }
    
        public int Id { get; set; }
        public int OID { get; set; }
        public string FK_BDNo { get; set; }
        public string FK_Xmz { get; set; }
        public string Columns { get; set; }
        public string Tasks { get; set; }
        public string Questions { get; set; }
    
        public virtual Process_BasicData Process_BasicData { get; set; }
        public virtual Process_ProjectGroup Process_ProjectGroup { get; set; }
        public virtual ICollection<Process_Subject_XuQiuFenXi> Process_Subject_XuQiuFenXi { get; set; }
        //
        public string FK_XMZName { get; set; }

    }
}
