//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Track
    {
        public int Id { get; set; }
        public string FK_Flow { get; set; }
        public string WorkID { get; set; }
        public string XMOID { get; set; }
        public string XQFXOID { get; set; }
        public string DYOID { get; set; }
        public string TCWTOID { get; set; }
        public string JJSLOID { get; set; }
        public string XSHOID { get; set; }
        public string SJSFOID { get; set; }
        public string SJSYOID { get; set; }
        public string DBFXOID { get; set; }
        public string DCJLOID { get; set; }
        public string LWZXOID { get; set; }
    }
}
