//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_SiLu
    {
        public Process_SiLu()
        {
            this.Process_XingShiHua = new HashSet<Process_XingShiHua>();
        }
    
        public int Id { get; set; }
        public int OID { get; set; }
        public string FK_BDNo { get; set; }
        public string Type { get; set; }
        public Nullable<int> FK_WTOID { get; set; }
    
        public virtual Process_BasicData Process_BasicData { get; set; }
        public virtual Process_TiChuWenTi Process_TiChuWenTi { get; set; }
        public virtual ICollection<Process_XingShiHua> Process_XingShiHua { get; set; }
        //
        public string FK_WTName { get; set; }
   
    }
}
