//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_ProjectGroup
    {
        public Process_ProjectGroup()
        {
            this.Process_GroupMember = new HashSet<Process_GroupMember>();
            this.Process_Project = new HashSet<Process_Project>();
        }
    
        public int Id { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string FK_GroupLeader { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Process_GroupMember> Process_GroupMember { get; set; }
        public virtual ICollection<Process_Project> Process_Project { get; set; }
        //
        public string FK_GroupMember { get; set; }
        public string FK_GroupMemberName { get; set; }
        public string FK_GroupLeaderName { get; set; }
        public string Projects { get; set; }

    }
}
