//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Subject_XuQiuFenXi
    {
        public int Id { get; set; }
        public int OID { get; set; }
        public string FK_BDNo { get; set; }
        public Nullable<int> FK_XmOID { get; set; }
        public string SourceDesc { get; set; }
        public string AnalysisResult { get; set; }
        public string TargetTask { get; set; }
        public string Innovation { get; set; }
    
        public virtual Process_BasicData Process_BasicData { get; set; }
        public virtual Process_Project Process_Project { get; set; }
        //
        public string FK_XmName { get; set; }

    }
}
