//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_DiaoYan
    {
        public int Id { get; set; }
        public int OID { get; set; }
        public string FK_BDNo { get; set; }
        public string SumType { get; set; }
        public string Sum { get; set; }
        public string SurveryAddr { get; set; }
        public string Investigator { get; set; }
        public string AnalysisResult { get; set; }
        public string AdvantageValue { get; set; }
        public string WeaknessValue { get; set; }
        public string UnsolvedProblem { get; set; }
        public string TechTrends { get; set; }
        public string BeyondPoint { get; set; }
    
        public virtual Process_BasicData Process_BasicData { get; set; }
    }
}
