//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_ShiYan
    {
        public Process_ShiYan()
        {
            this.Process_DuiBiFenXi = new HashSet<Process_DuiBiFenXi>();
        }
    
        public int Id { get; set; }
        public int OID { get; set; }
        public string FK_BDNo { get; set; }
        public string Design { get; set; }
        public string IndexSys { get; set; }
        public string RealizeStep { get; set; }
        public string TestCondition { get; set; }
        public string Data { get; set; }
        public string StatistacalResult { get; set; }
        public string Result { get; set; }
        public Nullable<int> FK_SFOID { get; set; }
    
        public virtual Process_BasicData Process_BasicData { get; set; }
        public virtual ICollection<Process_DuiBiFenXi> Process_DuiBiFenXi { get; set; }
        public virtual Process_SuanFa Process_SuanFa { get; set; }
        //
        public string FK_SFName { get; set; }

    }
}
