//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificResearchPrj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process_Attach
    {
        public int Id { get; set; }
        public int OID { get; set; }
        public string No_OID { get; set; }
        public string IsShenHe { get; set; }
        public string AttachName { get; set; }
        public string AttachDesc { get; set; }
        public string Path { get; set; }
    }
}
